version: '3'

services:
  dockertest:
    image: dockertest
    build:
      context: .
      dockerfile: DockerTest/Dockerfile

  mssql:
    image: microsoft/mssql-server-linux
    volumes:
      - mssql:/var/opt/mssql/data/
    container_name: hscarddb
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "5434:1433"

volumes:
   mssql: