version: '3'

services:
  dockertest:
    image: dockertest
    build:
      context: .
      dockerfile: DockerTest/Dockerfile
    depends_on:
      - db

  db:
    image: microsoft/mssql-server-linux
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"